// Script to generate HTML and CSS code for car list to the console output

class Brand {
    constructor(brandName, bgPosition, logoHeight, carsList) {
        this.brandName = brandName;
        this.bgPosition = bgPosition;
        this.logoHeight = logoHeight;
        this.carsList = carsList;
    }
}

let list = [
new Brand('ABARTH', '0 0', null, ['595 Convertible',
'595 Hatchback']),
new Brand('ALFA ROMEO', '-100px 0', null, ['Giulia Saloon',
'Stelvio Estate']),
new Brand('AUDI', '-200px -30px', '43px', ['A1 Sportback',
'A3 Saloon',
'A3 Saloon old',
'A3 Sportback',
'A4 Allroad Estate',
'A4 Estate',
'A4 Saloon',
'A5 Convertible',
'A5 Coupe',
'A5 Sportback',
'A6 Allroad Estate',
'A6 Estate',
'A6 Saloon',
'A7 Sportback',
'A8 Saloon',
'E-Tron Estate',
'E-Tron GT Saloon',
'E-Tron Sportback',
'Q2 Estate',
'Q3 Estate',
'Q3 Sportback',
'Q4 Estate',
'Q4 Sportback Estate',
'Q5 Estate',
'Q5 Sportback',
'Q7 Estate',
'Q8 Estate',
'R8 Convertible',
'R8 Coupe',
'RS 7 Sportback',
'RS Q3 Estate',
'RS Q3 Sportback',
'RS3 Saloon',
'RS3 Sportback',
'RS4 Avant',
'RS5 Coupe',
'RS5 Sportback',
'TT Convertible',
'TT Coupe',
'TT RS Convertible',
'TT RS Coupe']),
new Brand('BMW', '-400px 0', null, ['1 Series',
'2 Series Convertible',
'2 Series Coupe',
'2 Series Gran Coupe',
'2 Series Gran Tourer',
'2 Series Tourer',
'3 Series Saloon',
'3 Series Touring',
'4 Series Convertible',
'4 Series Coupe',
'4 Series Gran Coupe',
'5 Series Saloon',
'5 Series Touring Estate',
'7 Series Saloon',
'i3',
'i4 Gran Coupe',
'IX3 Estate',
'M4 Coupe',
'M5 Saloon',
'X1 Estate',
'X2',
'X3 Estate',
'X4 Estate',
'X4 M Estate',
'X5 Estate',
'X6 Estate',
'X7 Estate',
'Z4 Convertible']),
new Brand('CITROEN', '-700px -15px', '80px', ['Berlingo Estate',
'Berlingo L1 Van',
'Berlingo Van',
'C1',
'C3',
'C3 Aircross',
'C4 Hatchback',
'C5 Aircross',
'Dispatch M Van',
'e-C4',
'E-Space Tourer Electric Estate',
'Grand C4 Spacetourer Estate',
'Relay 35 L3 Van',
'Relay Luton',
'Relay Van',
'Space Tourer Estate'
]),
new Brand('CUPRA', '-700px -500px', null, ['Ateca Estate',
'Formentor Estate',
'Leon',
'Leon Estate']),
new Brand('DACIA', '-900px -10px', '90px', ['Duster Estate',
'Sandero',
'Sandero Stepway']),
new Brand('DS', '-500px -500px', null, ['DS3 Crossback','DS7']),
new Brand('FIAT', '-200px -100px', null, ['500',
'500 Convertible',
'500L',
'500X',
'Panda',
'Tipo Cross',
'Tipo New'
]),
new Brand('FORD', '-300px -125px', '50px', ['Ecosport',
'Fiesta',
'Focus',
'Focus Estate',
'Galaxy Estate',
'Grand Tourneo Connect Estate',
'Kuga Estate',
'Mondeo',
'Mondeo Estate',
'Mondeo Saloon',
'Mustang Convertible',
'Mustang Coupe',
'Mustang Mach-E',
'Puma',
'Ranger Pick-up',
'S-Max Estate',
'Tourneo Connect Estate',
'Transit Fridge Van']),
new Brand('HYUNDAI', '-500px -120px', '60px', ['Bayon',
'i10',
'i20',
'i30',
'i30 Estate',
'i30 Fastback',
'Ioniq',
'Ioniq 5',
'Kona',
'Santa Fe Estate',
'Tucson',
'Tucson Estate']),
new Brand('JAGUAR', '-800px -120px', '60px', ['i-Pace Estate']),
new Brand('JEEP', '-900px -130px', '40px', ['Compass Station Wagon',
'Renegade',
'Wrangler Hardtop']),
new Brand('KIA', '0 -220px', '60px', ['Ceed',
'Ceed Estate',
'Ceed Sportswagon',
'E-Niro Estate',
'EV6 Estate',
'Niro Estate',
'Picanto',
'Pro Ceed Estate',
'Rio',
'Sorento',
'Soul',
'Sportage Estate',
'Stonic Estate',
'XCeed Hatchback']),
new Brand('LEXUS', '-400px -215px', '75px', ['Es Saloon',
'LC Coupe',
'LS Saloon',
'NX Estate',
'RC Coupe',
'RX Estate',
'UX']),
new Brand('MAZDA', '-700px -210px', '85px', ['2 Hatchback',
'3 Hatchback',
'3 Saloon',
'6 Estate',
'6 Saloon',
'CX-30',
'CX-5 Estate',
'MX-30',
'MX-5 Convertible',
'MX-5 Rf Convertible']),
new Brand('MERCEDES', '-800px -200px', null, ['A Class',
'A Class AMG',
'A Class Saloon',
'AMG GT Convertible',
'AMG GT Coupe',
'B Class',
'C Class',
'C Class Coupe',
'C Class Estate',
'C Class Saloon',
'CLA Class Coupe',
'CLA Class Estate',
'CLS Coupe',
'E Class',
'E Class Coupe',
'E Class Estate',
'E Class Saloon',
'EQA Hatchback',
'EQC Estate',
'G Class Station Wagon',
'GLA',
'GLB Estate',
'GLC Coupe',
'GLC Estate',
'GLE Coupe',
'GLE Estate',
'GLS Estate',
'S Class Saloon',
'V Class Estate']),
new Brand('MG', '-900px -200px', null, ['HS Hatchback',
'MG3',
'MG5',
'ZS']),
new Brand('MINI', '0 -330px', '50px', ['Clubman Estate',
'Convertible',
'Countryman Hatch',
'Hatch']),
new Brand('NISSAN', '-300px -310px', '90px', ['370Z Coupe',
'Juke',
'Leaf',
'Micra',
'NV200 Estate',
'NV200 Van',
'NV250 L2 Van',
'Qashqai',
'X-Trail Station Wagon']),
new Brand('PEUGEOT', '-500px -315px', '80px', ['108',
'2008 Estate',
'208',
'3008 Estate',
'308',
'308 Estate',
'5008 Estate',
'508',
'508 Estate',
'Expert Compact Van',
'Expert Van',
'Partner Van',
'Rifter Estate',
'Traveller Estate']),
new Brand('POLESTAR', '0 0', null, ['2']),
new Brand('RENAULT', '0 -400px', null, ['Arkana Estate',
'Captur',
'Clio',
'Kadjar',
'Megane',
'Megane RS',
'Megane Sport Tourer',
'Zoe']),
new Brand('SEAT', '-200px -400px', null, ['Arona',
'Ateca Estate',
'Ibiza',
'Leon',
'Leon Estate',
'Mii',
'Tarraco Estate']),
new Brand('SKODA', '-400px -400px', null, ['ENYAQ iV',
'Kamiq Hatchback',
'Kodiaq Estate',
'Octavia',
'Octavia Estate',
'Scala',
'Superb',
'Superb Estate']),
new Brand('SMART', '-500px -430px', '40px', ['forfour',
'fortwo Cabrio',
'fortwo Coupe']),
new Brand('SUBARU', '-701px -420px', '60px', ['Impreza', 'XV']),
new Brand('SUZUKI', '-800px -400px', null, ['Ignis',
'Swace',
'Swift',
'SX4 S-Cross',
'Vitara Estate']),
new Brand('TESLA', '-1900px -400px', '75px', ['Model 3', 'Model S']),
new Brand('TOYOTA', '0 -515px', '75px', ['Aygo',
'C-HR',
'Camry Saloon',
'Corolla',
'Corolla Saloon',
'Corolla Touring Sport',
'Hilux Double Cab Pick-up',
'Land Cruiser Station Wagon',
'Prius',
'Proace LWB',
'Proace MWB',
'Proace Verso Estate',
'RAV4 Estate',
'Yaris']),
new Brand('VAUXHALL', '-100px -500px', null, ['Astra',
'Astra Estate',
'Combo Cargo Van',
'Combo Life Estate',
'Corsa',
'Crossland',
'Insignia',
'Mokka',
'Vivaro Crew Bus',
'Vivaro Life Estate',
'Vivaro Platform Cab',
'Vivaro Van']),
new Brand('VOLVO', '-300px -500px', null, ['S60 Saloon',
'S90 Saloon',
'V60 Estate',
'V90 Estate',
'XC40 Estate',
'XC60 Estate',
'XC90 Estate']),
new Brand('VW', '-200px -500px', null, ['Arteon',
'Arteon Shooting Brake',
'Caddy Estate',
'Caddy Van',
'California Estate',
'Caravelle Estate',
'Crafter Van',
'Golf Estate',
'Golf Mk8',
'ID.3',
'ID.4',
'Passat Estate',
'Passat Saloon',
'Polo New',
'T-Cross Estate',
'Tiguan Allspace Estate',
'Tiguan Estate',
'Touareg Estate',
'Touran Estate',
'Up'])
]

const section = document.createElement('section');
let backgroundStyle = '';

for (const brand of list) {
    const noSpaceBrandName = (brand.brandName).replaceAll(' ', '-');

    // create article
    const article = document.createElement('article');

    // generate brand logo
    backgroundStyle += `nav #car-list-menu input#${noSpaceBrandName} + label::before { background-position: ${brand.bgPosition};`;
    if(brand.logoHeight) {
        backgroundStyle += `height: ${brand.logoHeight};`;
    }
    backgroundStyle += '}';

    // generate brand name
    const input = document.createElement('input');
    input.type='checkbox';
    input.id = noSpaceBrandName;
    article.append(input);
    const label = document.createElement('label');
    label.setAttribute('for', noSpaceBrandName);
    label.innerText = brand.brandName;
    article.append(label);

    // generate cars
    const div = document.createElement('div');
    for (const car of brand.carsList) {
        const a = document.createElement('a');
        a.href = "#";
        a.innerText = car;
        div.append(a);
    }
    article.append(div);
    
    section.append(article);
}

// print output
console.log(section);
console.log(backgroundStyle);
